name: CI

on:
  push:
    branches: [ main, fix/refactor ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: cd Server && npm ci

      - name: TypeScript typecheck (server)
        run: cd Server && npx tsc -p tsconfig.json --noEmit

      - name: Run unit tests
        run: cd Server && npx vitest run --reporter dot
